version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
  cache:
    image: memcached
  redis:
    image: redis
  web:
    build: .
    env_file:
      - ./env/dev.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
      - redis